name: Convox Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: login
      uses: convox/action-login@v1
      with:
        password: ${{ secrets.CONVOX_DEPLOY_KEY }}
    - name: build
      id: build
      uses: convox/action-build@v1
      with:
        rack: convox/staging
        app: django
    - name: migrate
      uses: convox/action-run@v1
      with:
        rack: convox/staging
        app: django
        service: web
        release: ${{ steps.build.outputs.release }}
        command: "python manage.py migrate"
    - name: promote
      uses: convox/action-promote@v1
      with:
        rack: convox/staging
        app: django
        release: ${{ steps.build.outputs.release }}